- name: Install and configure Apache HTTP Server
  hosts: your_host
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        - wget
        - httpd
      vars:
        ansible_become_password: your_sudo_password

    - name: Download and extract repository archive
      shell: |
        cd /tmp
        wget https://github.com/utrains/static-resume/archive/refs/heads/main.zip
        unzip main.zip -d /tmp
      vars:
        ansible_become_password: your_sudo_password

    - name: Copy files to Apache document root
      shell: cp -r /tmp/static-resume-main/iPortfolio/* /var/www/html/
      vars:
        ansible_become_password: your_sudo_password

    - name: Start and enable Apache service
      systemd:
        name: httpd
        state: started
        enabled: yes

